### ISSUE TITLE
set_panel_userptr() fails with memory access violation

### ISSUE THREAD

**Issue by pjfarleyiii** [unicurses/unicurses#12]
The unicurses test program test_panels_advanced.py fails at the first set_panel_userptr statement.

```
C:\Python38\Lib\site-packages\unicurses\demos>python test_panels_advanced.py
Traceback (most recent call last):
  File "test_panels_advanced.py", line 58, in <module>
    set_panel_userptr(my_panels[0], my_panels[1])
  File "C:\Python38\lib\site-packages\unicurses.py", line 2392, in set_panel_userptr
    return pdlib.set_panel_userptr(pan_id, obj)
OSError: exception: access violation writing 0x00000000A64F43D8
```

The OS is Win10-64, python version is 3.8.3.  The pdcurses.dll was compiled from the v3.9 sources on the same system using nmake from VC Community edition 2019 V16.6.4 using make options WIDE=Y UTF8=Y and DLL=Y.

Not sure if this is unicurses or pdcurses.  Will try compiling the pdcurses v3.8 DLL and see if that makes a difference.

Will report back via comment later.

Peter

**Comment by pjfarleyiii** [comment]
I rebuilt pdcurses v3.9 using the VC build tools as suggested by the Python link here:

https://wiki.python.org/moin/WindowsCompilers

Which points to this MS download to use for Python 3.5 or greater:

https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2019

I recompiled using only DLL=Y in X64 mode because I installed Python 3.8.3 64-bit.

No matter the pdcurses compile options used it appears that we get this memory exception in the set_panel_userptr function, I think  when it tries to assign the passed pointer to the user member of the PANEL structure.

I tried changing the panel.h and panel.c members to make the user pointer just "void *" instead of "const void *" but that did not make a difference so I reverted that change.

I will just stay away from the userptr functions for now, but if you get a chance it would be helful of you could try debugging it too.  I'll leave an issue on the pdcurses github site but as there has not been much activity there for several years I am not holding my breath for a solution from there.

Regards,

Peter

**Comment by pjfarleyiii** [comment]
Just came back to this issue after a long hiatus due to RL issues.  This time it seems that the top_panel function is failing with an access violation (again, when called from a python script using the Unicurses wrapper).

I recompiled pdcurses in X64 native mode with DEBUG=Y and added PDC_LOG((...)) statements in many more of the panel.c functions so I could at least see who is actually being called, but I never get past the top_panel call.

I have a suspicion that since the then-working python 3.4 pdcurses implementation (which was, if I am not mistaken, a 32-bit compilation because python 3.4 was still 32-bit at that time), python 3 itself is now provided in a 64-bit version, which is what I am running on my Windows machine.

It is possible that the 64-bit compilation of pdcurses and the 64-bit python runtime are not interfacing cleanly (how large is a pointer variable in C now? 8 bytes or 4?  And what does python 64-bit think a pointer looks like and what does it do about it from the ctypes extension to a called DLL function?).

Any thoughts you may have about this would be appreciated.

Peter
